-- SQL Queries

# 1. Show all customer details.

SELECT * FROM customers;

# 2. List all products under the 'Electronics' category.

SELECT * FROM products
WHERE category = 'Electronics';

# 3. Find the total number of customers.
 
 SELECT COUNT(*) AS total_customers FROM CUSTOMERS;
 
# 4. Show all orders placed in May 2024. 

SELECT * FROM orders
WHERE MONTH(order_date) = 5 AND YEAR(order_date) = 2024;

# 5. Display the names of customers from ‘Nagpur’.

SELECT customer_name FROM Customers WHERE city = 'Nagpur';
 
# 6. Find total sales amount (sum of all orders).

SELECT SUM(total_amount) AS total_sales FROM Orders;

# 7. Show the number of orders per customer.

 SELECT c.customer_name, COUNT(o.order_id) AS total_orders
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name;
 
# 8. Find products with price greater than ₹10,000.

SELECT product_name, price FROM Products 
WHERE price > 10000;
 
# 9. List customers who joined after March 2024.

SELECT * FROM Customers WHERE join_date > '2024-03-31';

# 10. Display the order details with customer names and product names.

SELECT o.order_id, c.customer_name, p.product_name, od.quantity, od.price
FROM OrderDetails od
JOIN Orders o ON od.order_id = o.order_id
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Products p ON od.product_id = p.product_id;

# 11. Find total revenue generated by each product.

SELECT p.product_name, SUM(od.quantity * od.price) AS total_revenue
FROM OrderDetails od
JOIN Products p ON od.product_id = p.product_id
GROUP BY p.product_name;

# 12. Find top 3 customers by total purchase amount.

SELECT c.customer_name, SUM(o.total_amount) AS total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 3;

# 13. Find total sales per city.

SELECT c.city, SUM(o.total_amount) AS total_sales
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.city;

# 14. Find customers who purchased ‘Mobile’. 

SELECT DISTINCT c.customer_name
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN OrderDetails od ON o.order_id = od.order_id
JOIN Products p ON od.product_id = p.product_id
WHERE p.product_name = 'Mobile';

# 15. Calculate the average order value.

SELECT AVG(total_amount) AS avg_order_value FROM Orders;

# 16. Find total quantity sold per product category.

SELECT p.category, SUM(od.quantity) AS total_quantity_sold
FROM OrderDetails od
JOIN Products p ON od.product_id = p.product_id
GROUP BY p.category;

# 17. Show all products that have never been ordered. 

SELECT p.product_name
FROM Products p
LEFT JOIN OrderDetails od ON p.product_id = od.product_id
WHERE od.order_id IS NULL;


# 18. Get the highest single order value. 

SELECT MAX(total_amount) AS highest_order_value FROM Orders;

# 19. Find customers who ordered more than 2 products. 

SELECT c.customer_name, COUNT(od.product_id) AS products_ordered
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN OrderDetails od ON o.order_id = od.order_id
GROUP BY c.customer_name
HAVING COUNT(od.product_id) > 2;

# 20. Find which product generated the highest revenue.

SELECT p.product_name, SUM(od.quantity * od.price) AS total_revenue
FROM OrderDetails od
JOIN Products p ON od.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 1;

# 21. Show monthly sales trend (month-wise total sales).

SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, SUM(total_amount) AS monthly_sales
FROM Orders
GROUP BY month
ORDER BY month;
 
# 22. Rank customers by their total spending. 

SELECT c.customer_name, SUM(o.total_amount) AS total_spent,
RANK() OVER (ORDER BY SUM(o.total_amount) DESC) AS rank_order
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name;

# 23. Find products where stock is below 30. 

SELECT product_name, stock FROM Products WHERE stock < 30;

# 24. Calculate total revenue per category.

SELECT p.category, SUM(od.quantity * od.price) AS total_revenue
FROM OrderDetails od
JOIN Products p ON od.product_id = p.product_id
GROUP BY p.category;
 
# 25. Display total customers, total orders, and total revenue.

SELECT 
(SELECT COUNT(*) FROM Customers) AS total_customers,
(SELECT COUNT(*) FROM Orders) AS total_orders,
(SELECT SUM(total_amount) FROM Orders) AS total_revenue;

# 26. Find customer with highest order count.

SELECT c.customer_name, COUNT(o.order_id) AS total_orders
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC
LIMIT 1;

# 27. Show customers who spent more than ₹40,000 total.

SELECT c.customer_name, SUM(o.total_amount) AS total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING total_spent > 40000;

# 28. Find the average quantity of each product sold. 

SELECT p.product_name, AVG(od.quantity) AS avg_quantity_sold
FROM OrderDetails od
JOIN Products p ON od.product_id = p.product_id
GROUP BY p.product_name;

# 29. List all customers and their most recent order date.

SELECT c.customer_name, MAX(o.order_date) AS last_order_date
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name;
 
# 30. Find the percentage contribution of each product to total revenue.

SELECT p.product_name,
ROUND(SUM(od.quantity * od.price) * 100 / 
(SELECT SUM(quantity * price) FROM OrderDetails), 2) AS revenue_percent
FROM OrderDetails od
JOIN Products p ON od.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue_percent DESC;